version: 2.0
jobs:
  build:
    working_directory: /go/src/github.com/whywaita/gigani
    docker:
      - image: golang:latest
      - image: golang:1.9
    steps:
      - checkout
      - run:
          name: install dep
          command: go get github.com/golang/dep/...
      - run:
          name: dep ensure
          command: $GOPATH/bin/dep ensure
      - run:
          name: go test
          command: go test -v ./...
  deploy:
    working_directory: /go/src/github.com/whywaita/gigani
    docker:
      - image: golang:1.9
    steps:
      - checkout
      - run:
          name: install dep
          command: go get github.com/golang/dep/...
      - run:
          name: dep ensure
          command: $GOPATH/bin/dep ensure
      - run:
          command: go get github.com/mitchellh/gox
      - run:
          command: go get github.com/tcnksm/ghr
      - run:
          command: gox -osarch "linux/amd64 linux/arm darwin/amd64 windows/amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
      - run:
          command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --replace $(cat release_tag) dist/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /v(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)){2}/
