name: Manually execute
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Target URL'
        required: true
      format:
        description: 'Output format'
        required: true
        default: 'markdown'
      sort:
        description: 'Sort rule'
        required: true
        default: 'post'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "whywaita/gigani"
          version: "latest"
          file: "gigani_linux_amd64"
          target: "./gigani_linux_amd64"
      - run: |
          set -x

          sudo chmod +x ./gigani_linux_amd64
          ./gigani_linux_amd64 \
            -url ${{ github.event.inputs.url }} \
            -format ${{ github.event.inputs.format }} \
            -sort ${{ github.event.inputs.sort }}