name: Manually execute
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Target URL'
        required: true
      format:
        description: 'Output format'
        required: true
        default: 'markdown'
      sort:
        description: 'Sort rule'
        required: true
        default: 'post'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release file
        id: assets
        run: |
          set -eux

          latest_name=$(curl -s https://api.github.com/repos/whywaita/gigani/releases/latest | jq '.assets[].name' | grep linux_amd64 | tr -d '"')
          latest_url=$(curl -s https://api.github.com/repos/whywaita/gigani/releases/latest | jq '.assets[].browser_download_url' | grep linux_amd64 | tr -d '"')
          curl -L -O ${latest_url}

          tar zvfx ${latest_name}
      - name: Execute
        run: |
          set -eux

          sudo chmod +x ./gigani
          ./gigani \
            -url ${{ github.event.inputs.url }} \
            -format ${{ github.event.inputs.format }} \
            -sort ${{ github.event.inputs.sort }}